INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('aapl','Apple Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('abc','AmerisourceBergen Corporation C','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('abx','Barrick Gold Corporation Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('acia','Acacia Communications, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('aem','Agnico Eagle Mines Limited Comm','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('afl','AFLAC Incorporated Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ag','First Majestic Silver Corp. Ord','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('agb.v','ATLANTIC GOLD CORPORATION','VAN', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('agg','iShares Core U.S. Aggregate Bon','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('amd','Advanced Micro Devices, Inc.','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('amj','JPMorgan Chase Capital XVI JP M','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('amlp','Alerian MLP ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('amm.to','ALMADEN MINERALS LTD.','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('amzn','Amazon.com, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ashr','Deutsche X-Trackers Harvest CSI','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('auy','Yamana Gold Inc. Ordinary Share','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('avgo','Broadcom Limited','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('avxl','ANAVEX LIFE SCIENCES','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('bac','Bank of America Corporation Com','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('bcs','Barclays PLC Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('bmy','Bristol-Myers Squibb Company Co','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('c','Citigroup, Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cat','Caterpillar, Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cbb','Cincinnati Bell Inc. Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cbg','CBRE Group Inc Common Stock Cla','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ccm.to','CANARC RES J','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cde','Coeur Mining, Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cien','Ciena Corporation Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('clms','Calamos Asset Management, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('clr','Continental Resources, Inc. Com','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cnr.to','CANADIAN NATIONAL RAILWAY CO.','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cnx','CONSOL Energy Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cnxr','Connecture, Inc.','NGM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cod.l','SAINT GOBAIN','LSE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('cve.to','CENOVUS ENERGY INC.','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('d','Dominion Resources, Inc. Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dbc','PowerShares DB Commodity Index','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dgld','Credit Suisse AG','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dks','Dick''s Sporting Goods Inc Commo','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dug','ProShares UltraShort Oil & Gas','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dust','Direxion Daily Gold Miners Inde','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('dwti','VS 3X INV WTI CRUDE','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ech','iShares MSCI Chile Capped Inves','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ecr','Eclipse Resources Corporation C','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('edz','Direxion Emerging Markets Bear','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('eem','iShares MSCI Emerging Index Fun','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('efa','iShares MSCI EAFE ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('egn','Energen Corporation Common Stoc','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('egt.v','EGUANA TECHNOLOGIES INC','VAN', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('emb','iShares J,P. Morgan USD Emergin','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('epi','WisdomTree India Earnings Fund','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ete','Energy Transfer Equity, L.P. En','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('etfc','E*TRADE Financial Corporation','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ew','Edwards Lifesciences Corporatio','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ewa','iShares MSCI Australia Index Fu','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ewc','iShares MSCI Canada Index Fund','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ewg','iShares MSCI Germany Index Fund','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ewu','iShares MSCI United Kingdom ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ewz','iShares MSCI Brazil Capped Inde','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('exar','Exar Corporation Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('fb','Facebook, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('fmsa','Fairmount Santrol Holdings Inc.','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('fxi','iShares China Large-Cap ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gale','Galena Biopharma, Inc.','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gdsi','GLOBAL DIGITAL SOLTN','PNK', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gdx','VanEck Vectors Gold Miners ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gdxj','VanEck Vectors Junior Gold Mine','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gig','GigPeak, Inc. Common Stock','ASE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gld','SPDR Gold Trust','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('goog','Alphabet Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('googl','Alphabet Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('grcu','GREEN CURES & BOTANI','PNK', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('gs','Goldman Sachs Group, Inc. (The)','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hd','Home Depot, Inc. (The) Common S','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hl','Hecla Mining Company Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hod.to','HORIZON BETA PRO NYMEX CRDE OIL','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hou.to','HORIZON BETAPRO NYMEX CRDE OIL','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hukx.l','HSBC FTSE 100 GBP','LSE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hwbk','Hawthorn Bancshares, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hwcc','Houston Wire & Cable Company','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hyg','iShares iBoxx $ High Yield Corp','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('hzn','Horizon Global Corporation Comm','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('i','Intelsat S.A. Common Shares','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('iart','Integra LifeSciences Holdings C','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ibb','iShares Nasdaq Biotechnology In','NGM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ief','iShares 7-10 Year Treasury Bond','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('inda','Ishares MSCI India ETF','BTS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('intc','Intel Corporation','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('intu','Intuit Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ir','Ingersoll-Rand plc (Ireland)','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('isl.l','IS SOLUTIONS','LSE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ive','iShares S&P 500 Value ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('iwm','iShares Russell 2000 ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('iyr','iShares U.S. Real Estate ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('iyz','iShares U.S. Telecommunications','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('jnk','SPDR Barclays High Yield Bond E','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('jnug','Direxion Daily Junior Gold Mine','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('jpm','JP Morgan Chase & Co. Common St','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('kbe','SPDR S&P Bank ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('kr','Kroger Company (The) Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('labu','Direxion Daily S&P Biotech Bull','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('lnc','Lincoln National Corporation Co','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('lqd','iShares iBoxx $ Investment Grad','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ma','Mastercard Incorporated Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mbly','Mobileye N.V. Ordinary Shares','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mdt','Medtronic plc. Ordinary Shares','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mgt','MGT Capital Investments Inc Com','ASE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mos','Mosaic Company (The) Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mtd','Mettler-Toledo International, I','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('mu','Micron Technology, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('navi','Navient Corporation','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('nete','Net Element, Inc.','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('nke','Nike, Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('nofix','Northern Funds Fixed Income Fun','NAS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('nugt','Direxion Daily Gold Miners Inde','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('oih','VanEck Vectors Oil Services ETF','ASE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('once','Spark Therapeutics, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('orcl','Oracle Corporation Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('paas','Pan American Silver Corp.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pih','1347 Property Insurance Holding','NGM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pii','Polaris Industries Inc. Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pir','Pier 1 Imports, Inc. Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pjc','Piper Jaffray Companies Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pjt','PJT Partners Inc. Class A Commo','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pkbk','Parke Bancorp, Inc.','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pkg','Packaging Corporation of Americ','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pot','Potash Corporation of Saskatche','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pot.to','POTASH CORP OF SASK INC','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('pou.to','PARAMOUNT RESOURCES LTD.','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('prlb','Proto Labs, Inc. Common stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('rcl','Royal Caribbean Cruises Ltd. Co','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('rig','Transocean Ltd (Switzerland) Co','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('rsp','Guggenheim S&P 500 Equal Weight','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('rsx','VanEck Vectors Russia ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('rusl','Direxion Daily Russia Bull 3x S','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('scty','SolarCity Corporation','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('sds','ProShares UltraShort S&P500','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('sh','ProShares Short S&P500','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('shw','Sherwin-Williams Company (The)','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('sil','Global X Silver Miners ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('slv','iShares Silver Trust','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('smh','VanEck Vectors Semiconductor ET','ASE', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('styax','Wells Fargo Core Plus Bond Fund','NAS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('sunw','Sunworks, Inc.','NCM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('sync','Synacor, Inc.','NGM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('t','AT&T Inc.','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('taho','Tahoe Resources, Inc. Ordinary','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tbt','ProShares UltraShort Lehman 20','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tip','iShares TIPS Bond ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tjx','TJX Companies, Inc. (The) Commo','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tna','Direxion Small Cap Bull 3X Shar','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tsla','Tesla Motors, Inc.','NMS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tvix','Credit Suisse AG','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('tza','Direxion Small Cap Bear 3X Shar','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ua','Under Armour, Inc. Class A Comm','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('udn','PowerShares DB USD Index Bearis','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uge','ProShares Ultra Consumer Goods','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uis','Unisys Corporation New Common S','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('ung','United States Natural Gas Fund','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('unis','Unilife Corporation','NGM', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uscox','US Global Investors Funds China','NAS', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uslv','Credit Suisse AG','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uso','United States Oil Fund','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uup','PowerShares DB USD Index Bullis','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uvxy','ProShares Trust Ultra VIX Short','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('uwti','VS 3X WTI CRUDE','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('vlo','Valero Energy Corporation Commo','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('vrx','Valeant Pharmaceuticals Interna','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('vwo','Vanguard FTSE Emerging Markets','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('vxx','iPath S&P 500 VIX Short Term Fu','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('w','Wayfair Inc. Class A Common Sto','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('wab','Westinghouse Air Brake Technolo','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('wage','WageWorks, Inc. Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('wair','Wesco Aircraft Holdings, Inc. C','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('wat','Waters Corporation Common Stock','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('wcn','Waste Connections, Inc. Common','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('whr','Whirlpool Corporation Common St','NYQ', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xbi','SPDR Series Trust  SPDR S&P Bio','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xeg.to','iSHARES SP TSX CAPPED ENERGY IN','TOR', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xhb','SPDR Series Trust SPDR Homebuil','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xiv','Credit Suisse AG','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlb','Materials Select Sector SPDR','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xle','SPDR Select Sector Fund - Energ','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlf','SPDR Select Sector Fund - Finan','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xli','SPDR Select Sector Fund - Indus','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlk','SPDR Select Sector Fund - Techn','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlp','SPDR Select Sector Fund - Consu','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlu','SPDR Select Sector Fund - Utili','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xlv','SPDR Select Sector Fund - Healt','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xly','SPDR Select Sector Fund - Consu','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xme','SPDR S&P Metals & Mining ETF','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('xop','SPDR S&P Oil & Gas Explor & Pro','PCX', 'USD', 'USA', 'active', NOW(), NOW());
INSERT INTO stock(symbol, name, market, currency, country, status, created, updated) VALUES('yinn','Direxion Daily FTSE China Bull','PCX', 'USD', 'USA', 'active', NOW(), NOW());